AWSTemplateFormatVersion: 2010-09-09
Description: |
  Parent stack for PII redaction using AWS services with a Docker image.

Resources:

  TransformToDocxLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "TransformToDocxLambdaPolicy-${AWS::StackName}"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${AWS::Region}-${AWS::AccountId}-destination-bucket/*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${AWS::Region}-${AWS::AccountId}-docx-bucket/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      RoleName: !Sub "TransformToDocxLambdaRole-${AWS::StackName}"

  TransformToDocxLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TransformToDocxLambdaFunction
      Role: !GetAtt TransformToDocxLambdaRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/my-lambda-repo:latest"
      Environment:
        Variables:
          DESTINATION_BUCKET: !Sub "${AWS::Region}-${AWS::AccountId}-destination-bucket"
          DOCX_BUCKET: !Sub "${AWS::Region}-${AWS::AccountId}-docx-bucket"
      Timeout: 300
      MemorySize: 1024
      
  BucketNotification:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::Region}-${AWS::AccountId}-destination-bucket"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt TransformToDocxLambdaFunction.Arn

  DocxBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::Region}-${AWS::AccountId}-docx-bucket"

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TransformToDocxLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${AWS::Region}-${AWS::AccountId}-destination-bucket"
