AWSTemplateFormatVersion: 2010-09-09
Description: |
  Nested stack for S3 event notification configuration.


Resources:
  S3BucketNotification:
    Type: Custom::S3BucketNotification
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:AWSLambdaBasicExecutionRole"
      BucketName: !Sub "${AWS::Region}-${AWS::AccountId}-destination-bucket"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:TransformToDocxLambdaFunction"
